### PR TITLE
get hookedSAETransformer + tutorial working

### PR DESCRIPTION
**Pull request by dtch1997**
# Description

Updates Joseph's HookedSAETransformer to current codebase

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have not rewritten tests relating to key interfaces which would affect backward compatibility

### You have tested formatting, typing and unit tests (acceptance tests not currently in use)

- [ ] I have run `make check-ci` to check format and linting. (you can run `make format` to format code if needed.)

### Performance Check.

If you have implemented a training change, please indicate precisely how performance changes with respect to the following metrics:
- [ ] L0
- [ ] CE Loss
- [ ] MSE Loss
- [ ] Feature Dashboard Interpretability

Please links to wandb dashboards with a control and test group.

### CODE REVIEW

**Comment by ArthurConmy** [comment]
Why is code being copy and pasted over from transformer lens? Is it not possible to just use `transformer_lens.HookedTransformer`: https://github.com/neelnanda-io/TransformerLens/pull/536?

**Comment by jbloomAus** [comment]
> Why is code being copy and pasted over from transformer lens? Is it not possible to just use `transformer_lens.HookedSAETransformer`: [neelnanda-io/TransformerLens#536](https://github.com/neelnanda-io/TransformerLens/pull/536)?

@ArthurConmy This was a tough call for me but I think it's probably the right one. T-lens implements it's own SAE which has a few dissimilarities to ours and which might change / go out of sync. Part of this was that I tried to use the T-lens one with SAE Lens and it needed enough changes that don't make sense as PR's to T-lens that I thought it might be best to duplicate / get them in sync. 

However, this thinking is cached from a couple of weeks ago and my conviction is less strong now without more context. Possibly worth trying to enumerate the challenges and make changes to my SAE class of the HookedSAE transformer class such that this isn't necessary.

**Comment by ArthurConmy** [comment]
@jbloomAus there is definitely a problem with too many SAEs classes. I think there probably should be one training SAE (likely the SAE in this codebase) and one inference SAE (used for circuit analysis and feature viz), but currently we have

1) SAE for training in this lib
2) SAE for inference in TransformerLens
3) SAE for inference (feature analysis) in sae_vis
4) This proposal too

Which seems too many (already, the fact I had to use 3) and 2) when doing steering vectors work sucked IMO)

**Comment by jbloomAus** [comment]
@dtch1997 Thanks for this! We now have hooked SAE transformer. I appreciate you doing this and sorry how it turned out with duplicate work. Will try to find a way to make it up to you.

**Pull request closed without merging**
