### PR TITLE
Updated pyproject.toml to use TL ^2.0, and to use fork of sae-vis tha…

### PR DESCRIPTION
**Pull request by curt-tigges**
…t also uses TL ^2.0

# Description

Addresses https://github.com/jbloomAus/SAELens/issues/209 by updating to use TransformerLens ^2.0.0. In order to do this, I also needed to fork and modify sae-lens since it is not compatible with TL ^2.0.0. Thus, the changes rely on my current fork, but I propose making a PR to sae-vis so that we can go back to relying directly on the main library.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have not rewritten tests relating to key interfaces which would affect backward compatibility

### You have tested formatting, typing and unit tests (acceptance tests not currently in use)

- [x] I have run `make check-ci` to check format and linting. (you can run `make format` to format code if needed.)

### CODE REVIEW

**Comment by chanind** [comment]
I don't think we publish the library to PyPI while depending on a module on git. Can you open a PR to sae-vis with your change so it can also publish the TL2.0 version to PyPI?

**Comment by jbloomAus** [comment]
I think we should just depend on SAE Dashboard instead of SAE Vis. https://github.com/jbloomAus/SAEDashboard

Since we're planning to move over to that anyway. This seems like a reason for us to make sure SAE Dashboard is documented well enough and to make tutorials in SAE Lens refer to it instead of SAE Vis.

**Comment by jbloomAus** [comment]
Edit: @curt-tigges I'd rather SAE Lens not depend on SAE Dashboard at all! SAE Dashboard will need to depend on SAE Lens and I'd like to avoid circular dependencies.

**Comment by curt-tigges** [comment]
I did a brief check and didn't see any SAELens code using sae-vis or SAEDashboard directly, but I can do a more careful check to make sure and remove the dependencies.

**Comment by curt-tigges** [comment]
Updated to remove reliance on sae-vis and SAEDashboard. Notebooks have install commands included.

In order to make the tests pass with TL ^2.0.0, I added an error handler for the `get_activations` function, but this might be an issue that TransformerLens should address (the view command failed, but reshape worked).

**Pull request merged**
