### PR TITLE
Move activation store to cpu

### PR DESCRIPTION
**Pull request by tomMcGrath**
# Description

Currently the ActivationStore class stores the activation buffer (which is typically large) in the same location as the model; this location is normally VRAM which is a scarce resource. 

This PR allows the ActivationStore to store the activation buffer on a different device, including CPU. The device to use is specified by the new `act_store_device` config entry, which defaults to using the same device as the model to ensure backwards compatibility.

The linked W&B dashboard below demonstrates that this change has no effect on throughput vs storing activations in VRAM for a typical workload and allows at least an 8x scaleup of activation buffer size.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not rewritten tests relating to key interfaces which would affect backward compatibility

### You have tested formatting, typing and unit tests (acceptance tests not currently in use)

- [x] I have run `make check-ci` to check format and linting. (you can run `make format` to format code if needed.)

### Performance Check.

If you have implemented a training change, please indicate precisely how performance changes with respect to the following metrics:
- [x] L0
- [x] CE Loss
- [x] MSE Loss
- [ ] Feature Dashboard Interpretability

This is a performance improvement: increasing metrics is not the goal. This PR maintains throughput while freeing up VRAM: see [W&B dashboard](https://wandb.ai/tmcgrath/gpt-2-sweep-21may24-acts-to-cpu/workspace).

### CODE REVIEW

**Comment by jbloomAus** [comment]
Seems good. Do you have a moment to write a few tests? Bit nervous we could have a bug and not realise it here.

**Comment by tomMcGrath** [comment]
Sure, will add some to this pr

**Comment by tomMcGrath** [comment]
I've added some tests and fixed an issue in the test cacher + an issue the new tests exposed in my code.

**Comment by jbloomAus** [comment]
Awesome work! Thanks!

**Pull request merged**
